spring:
  application:
    name: demo
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      format-sql: true
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://localhost:5432/cota
    username: cota
    password: cotaatoc
    driverClassName: org.postgresql.Driver
server:
  port: 7777
